# Generated by Django 4.1.7 on 2023-04-19 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
