# Generated by Django 4.1.7 on 2023-05-04 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_visit_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='calle',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voto',
            name='apellido',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='voto',
            name='nombre_persona',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
