# Generated by Django 4.1.7 on 2023-05-04 20:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_calle_fecha_hora_voto_apellido_voto_nombre_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='voto',
            name='fecha_hora',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
