# Generated by Django 4.1.7 on 2023-05-05 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0007_voto_fecha_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='calle',
            name='fecha_finalizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
