# Generated by Django 4.1.7 on 2023-05-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0008_calle_fecha_finalizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='calle',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
