# Generated by Django 4.2 on 2023-05-18 23:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0009_calle_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='voto',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voto',
            name='confirmation_token',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='voto',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
