# Generated by Django 4.2 on 2023-05-18 23:54

from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('first', '0010_voto_confirmado_voto_confirmation_token_voto_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='confirmation_token',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255),
        ),
    ]
